name: zindi-akeed
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip
  - invoke
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - path.py
  - python=3.7
  - scikit-learn
  - seaborn
  - statsmodels
  - conda-forge::geopandas
  - geoviews
  - pip:
      - lightgbm
      - xgboost
      - catboost
      - mlxtend
      - eli5
      - missingno
      - hvplot
